#ifndef __VERSION_H__
#define __VERSION_H__
#define SYSTEM_SOFTWARE_VERSION "V:0138"
#define SYSTEM_HARDWARE_VERSION "V:0101"
#define SYSTEM_RELVERSION_TIME "210325"
#define CONFIG_PRODUCT_WNAVY 1
#endif
